export const PASSWORD_REGEX = /^(?=.*[a-z]).{6,}$/gm;

export const PHONE_NUMBER_REGEX = /^[\+][(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/gim;

export const PASSPORT_REGEX = /^[A-z0-9]{2,3}[0-9]{6}$/gm;

export const VAT_REGEX =
  /(?:(AT)\s*(U\d{8}))|(?:(BE)\s*(0?\d{*}))|(?:(CZ)\s*(\d{8,10}))|(?:(DE)\s*(\d{9}))|(?:(CY)\s*(\d{8}[A-Z]))|(?:(DK)\s*(\d{8}))|(?:(EE)\s*(\d{9}))|(?:(GR)\s*(\d{9}))|(?:(ES|NIF:?)\s*([0-9A-Z]\d{7}[0-9A-Z]))|(?:(FI)\s*(\d{8}))|(?:(FR)\s*([0-9A-Z]{2}\d{9}))|(?:(GB)\s*((\d{9}|\d{12})~(GD|HA)\d{3}))|(?:(HU)\s*(\d{8}))|(?:(IE)\s*(\d[A-Z0-9\\+\\*]\d{5}[A-Z]))|(?:(IT)\s*(\d{11}))|(?:(LT)\s*((\d{9}|\d{12})))|(?:(LU)\s*(\d{8}))|(?:(LV)\s*(\d{11}))|(?:(MT)\s*(\d{8}))|(?:(NL)\s*(\d{9}B\d{2}))|(?:(PL)\s*(\d{10}))|(?:(PT)\s*(\d{9}))|(?:(SE)\s*(\d{12}))|(?:(SI)\s*(\d{8}))|(?:(SK)\s*(\d{10}))|(?:\D|^)(\d{11})(?:\D|$)|(?:(CHE)(-|\s*)(\d{3}\.\d{3}\.\d{3}))|(?:(SM)\s*(\d{5}))/gi;
export const ALL_BUT_NUMBERS_REGEX = /[^0-9]/g;
export const FOUR_DIGITS_REGEX = /.{1,4}/g;
export const ALL_BUT_NUMBERS_AND_SLASH_REGEX = /[^(0-9 | /)]/g;

export const dateTimeFormat = "dd/MM/yyyy HH:mm:ss";

export const languagesAndLocales = [
  {
    lang: "zh",
    locale: "zh_CN",
  },
  {
    lang: "en",
    locale: "en_US",
  },
  {
    lang: "ru",
    locale: "ru_RU",
  },
  {
    lang: "ro",
    locale: "ro_RO",
  },
  {
    lang: "fr",
    locale: "fr_FR",
  },
  {
    lang: "de",
    locale: "de_DE",
  },
  {
    lang: "es",
    locale: "es_ES",
  },
  {
    lang: "it",
    locale: "it_IT",
  },
  {
    lang: "tr",
    locale: "tr_TR",
  },
];

export const languagesData = [
  {
    label: {
      ru: "Русский",
      en: "Английский",
      ro: "Румынский",
      es: "Испанский",
      fr: "Французский",
      de: "Немецкий",
      it: "Итальянский",
      zh: "Китайский",
      tr: "Турецкий",
    },
    lang: "ru",
  },
  {
    label: {
      ru: "Russian",
      en: "English",
      ro: "Romanian",
      es: "Spanish",
      fr: "French",
      de: "German",
      it: "Italian",
      zh: "Chinese",
      tr: "Turkish",
    },
    lang: "en",
  },
  {
    label: {
      ru: "Rusă",
      en: "Engleză",
      ro: "Română",
      es: "Spaniolă",
      fr: "Franceză",
      de: "Germană",
      it: "Italiană",
      zh: "Chineză",
      tr: "Turcă",
    },
    lang: "ro",
  },
  {
    label: {
      ru: "Ruso",
      en: "Inglés",
      ro: "Rumano",
      es: "Español",
      fr: "Francés",
      de: "Alemán",
      it: "Italiano",
      zh: "Chino",
      tr: "Turco",
    },
    lang: "es",
  },
  {
    label: {
      ru: "Russe",
      en: "Anglais",
      ro: "Roumain",
      es: "Espagnol",
      fr: "Français",
      de: "Allemand",
      it: "Italien",
      zh: "Chinois",
      tr: "Turc",
    },
    lang: "fr",
  },
  {
    label: {
      ru: "Russisch",
      en: "Englisch",
      ro: "Rumänisch",
      es: "Spanisch",
      fr: "Französisch",
      de: "Deutsch",
      it: "Italienisch",
      zh: "Chinesisch",
      tr: "Türkisch",
    },
    lang: "de",
  },
  {
    label: {
      ru: "Russo",
      en: "Inglese",
      ro: "Rumeno",
      es: "Spagnolo",
      fr: "Francese",
      de: "Tedesco",
      it: "Italiano",
      zh: "Cinese",
      tr: "Turco",
    },
    lang: "it",
  },
  {
    label: {
      ru: "俄语",
      en: "英语",
      ro: "罗马尼亚语",
      es: "西班牙语",
      fr: "法语",
      de: "德语",
      it: "意大利语",
      zh: "中文",
      tr: "土耳其语",
    },
    lang: "zh",
  },
  {
    label: {
      ru: "Rusça",
      en: "İngilizce",
      ro: "Rumence",
      es: "İspanyolca",
      fr: "Fransızca",
      de: "Almanca",
      it: "İtalyanca",
      zh: "Çince",
      tr: "Türkçe",
    },
    lang: "tr",
  },
];

export const languagesMockups = [
  { label: "English", value: "en" },
  { label: "Русский", value: "ru" },
  { label: "Română", value: "ro" },
  { label: "Español", value: "es" },
  { label: "Français", value: "fr" },
  { label: "Deutsch", value: "de" },
  { label: "Italiano", value: "it" },
  { label: "中文", value: "zh" },
  { label: "Türkçe", value: "tr" },
];
export const languages = languagesMockups.map((lang) => lang.value);

export const currenciesMockups = [
  { label: "British Pound Sterling (GBP)", value: "gbp" },
  { label: "Chinese Yuan Renminbi (CNY)", value: "cny" },
  { label: "Euro (EUR)", value: "eur" },
  { label: "Indian Rupee (INR)", value: "inr" },
  { label: "Kazakhstani Tenge (KZT)", value: "kzt" },
  { label: "Moldovan Leu (MDL)", value: "mdl" },
  { label: "Romanian Leu (RON)", value: "ron" },
  { label: "Russian Ruble (RUB)", value: "rub" },
  { label: "Turkish Lira (TRY)", value: "try" },
  { label: "United States Dollar (USD)", value: "usd" },
];

export const timezonesMockups = [
  { label: "UTC-12:00 - Baker Island Time", value: "UTC-12:00" },
  { label: "UTC-11:00 - Niue Time, Samoa Standard Time", value: "UTC-11:00" },
  { label: "UTC-10:00 - Hawaii-Aleutian Standard Time, Cook Island Time", value: "UTC-10:00" },
  { label: "UTC-09:00 - Alaska Standard Time, Gambier Island Time", value: "UTC-09:00" },
  { label: "UTC-08:00 - Pacific Standard Time", value: "UTC-08:00" },
  { label: "UTC-07:00 - Mountain Standard Time", value: "UTC-07:00" },
  { label: "UTC-06:00 - Central Standard Time", value: "UTC-06:00" },
  { label: "UTC-05:00 - Eastern Standard Time", value: "UTC-05:00" },
  { label: "UTC-04:00 - Atlantic Standard Time", value: "UTC-04:00" },
  { label: "UTC-03:00 - Argentina Time, Atlantic Time, Brasilia Time", value: "UTC-03:00" },
  { label: "UTC-02:00 - Fernando de Noronha Time, South Georgia Time", value: "UTC-02:00" },
  { label: "UTC-01:00 - Azores Time, Cape Verde Time", value: "UTC-01:00" },
  { label: "UTC±00:00 - Greenwich Mean Time, Western European Time", value: "UTC±00:00" },
  {
    label: "UTC+01:00 - Central European Time, West Africa Time, Kaliningrad Time (Russia)",
    value: "UTC+01:00",
  },
  {
    label:
      "UTC+02:00 - Eastern European Time, Central Africa Time, Moscow Standard Time (Russia), Samara Time (Russia)",
    value: "UTC+02:00",
  },
  { label: "UTC+03:00 - Eastern African Time, Arabia Standard Time", value: "UTC+03:00" },
  {
    label: "UTC+04:00 - Gulf Standard Time, Mauritius Time, Yekaterinburg Time (Russia)",
    value: "UTC+04:00",
  },
  {
    label: "UTC+05:00 - Pakistan Standard Time, Maldives Time, Omsk Time (Russia)",
    value: "UTC+05:00",
  },
  { label: "UTC+05:30 - Indian Standard Time, Sri Lanka Time", value: "UTC+05:30" },
  {
    label: "UTC+06:00 - Bangladesh Standard Time, Bhutan Time, Novosibirsk Time (Russia)",
    value: "UTC+06:00",
  },
  { label: "UTC+06:30 - Cocos Islands Time", value: "UTC+06:30" },
  {
    label: "UTC+07:00 - Indochina Time, Western Indonesia Time, Krasnoyarsk Time (Russia)",
    value: "UTC+07:00",
  },
  {
    label: "UTC+08:00 - China Standard Time, Philippine Standard Time, Irkutsk Time (Russia)",
    value: "UTC+08:00",
  },
  { label: "UTC+08:45 - Southeastern Western Australia Standard Time", value: "UTC+08:45" },
  {
    label: "UTC+09:00 - Japan Standard Time, Korea Standard Time, Yakutsk Time (Russia)",
    value: "UTC+09:00",
  },
  { label: "UTC+09:30 - Australian Central Standard Time", value: "UTC+09:30" },
  {
    label: "UTC+10:00 - Australian Eastern Standard Time, Vladivostok Time (Russia)",
    value: "UTC+10:00",
  },
  { label: "UTC+10:30 - Lord Howe Standard Time", value: "UTC+10:30" },
  {
    label: "UTC+11:00 - Solomon Island Time, Vanuatu Time, Magadan Time (Russia)",
    value: "UTC+11:00",
  },
  { label: "UTC+11:30 - Norfolk Island Time", value: "UTC+11:30" },
  {
    label: "UTC+12:00 - New Zealand Standard Time, Fiji Time, Kamchatka Time (Russia)",
    value: "UTC+12:00",
  },
  { label: "UTC+12:45 - Chatham Standard Time", value: "UTC+12:45" },
  { label: "UTC+13:00 - Samoa Standard Time", value: "UTC+13:00" },
  { label: "UTC+14:00 - Line Islands Time", value: "UTC+14:00" },
];

export enum RequestStatus {
  CREATED = "CREATED",
  ACCEPTED = "ACCEPTED",
  COMPLETED = "COMPLETED",
  REJECTED = "REJECTED",
  WITHDRAWN = "WITHDRAWN",
}

export const statuses = [
  {
    lang: "de",
    label: {
      created: "Erstellt",
      accepted: "Akzeptiert",
      completed: "Vollendet",
    },
  },
  {
    lang: "en",
    label: {
      created: "Created",
      accepted: "Accepted",
      completed: "Completed",
    },
  },
  {
    lang: "es",
    label: {
      created: "Creado",
      accepted: "Aceptado",
      completed: "Terminado",
    },
  },
  {
    lang: "fr",
    label: {
      created: "Créé",
      accepted: "Accepté",
      completed: "Complété",
    },
  },
  {
    lang: "it",
    label: {
      created: "Creato",
      accepted: "Accettato",
      completed: "Completato",
    },
  },
  {
    lang: "ro",
    label: {
      created: "Creată",
      accepted: "Admis",
      completed: "Efectuat",
    },
  },
  {
    lang: "ru",
    label: {
      created: "Создан",
      accepted: "Принят",
      completed: "Выполнен",
    },
  },
  {
    lang: "zh",
    label: {
      created: "创建",
      accepted: "公认",
      completed: "完全的",
    },
  },
];

export enum RequestServeType {
  IMMEDIATELY = "IMMEDIATELY",
  BY_SPECIFIC_TIME = "BY_SPECIFIC_TIME",
}

export enum IroningRequestType {
  BRING = "BRING",
  TAKEOUT = "TAKEOUT",
}

export enum RequestPaymentPlaceType {
  ROOM = "ROOM",
  AT_CHECKOUT = "AT_CHECKOUT",
}

export enum RequestPaymentPlaceTypeLabel {
  "ROOM" = "В комнате",
  "AT_CHECKOUT" = "На рецепции",
}

export enum NotificationType {
  PAYMENT = "PAYMENT",
  ROOMS_QUANTITY_CHANGE_REQUEST = "ROOMS_QUANTITY_CHANGE_REQUEST",
  PAYMENT_RECEIPT = "PAYMENT_RECEIPT",
  HOTEL_REQUEST_CREATED = "HOTEL_REQUEST_CREATED",
}

export enum NotificationTypeLabel {
  "PAYMENT" = "уведомление об оплате",
  "ROOMS_QUANTITY_CHANGE_REQUEST" = "Запрос на увеличение количества номеров",
  "PAYMENT_RECEIPT" = "Запрос квитанции об оплате",
  "HOTEL_REQUEST_CREATED" = "new_request",
}

export enum NotificationTypeLabelDefault {
  "PAYMENT" = "уведомление об оплате",
  "ROOMS_QUANTITY_CHANGE_REQUEST" = "Запрос на увеличение количества номеров",
  "PAYMENT_RECEIPT" = "Запрос квитанции об оплате",
  "HOTEL_REQUEST_CREATED" = "новый запрос",
}

export enum RequestPaymentType {
  CASH = "CASH",
  CARD = "CARD",
}

export enum RequestPaymentTypeLabel {
  "CASH" = "cash",
  "CARD" = "payment_by_card_visa_mastercard",
}

export enum RequestStaffTypeLabel {
  "plumber" = "Проблемы с сантехникой",
  "TV" = "Проблемы с настройкой ТВ",
  "light" = "Перегорела лампочка",
}

export enum CategoryLabelDefault {
  "CHAT" = "Чат",
  "RECEPTION" = "Рецепция",
  "RESTAURANT" = "Ресторан",
  "ROOM_SERVICE" = "Рум-сервис",
  "SPA" = "Фитнес-зона",
  "SHOP" = "Магазин отеля",
}

export enum RequestTypeLabelDefault {
  "FOOD_ORDER" = "Заказ еды",
  "BRING_DISHES" = "Запросить посуду",
  "WASH_DISHES" = "Убрать грязную посуду",
  "IRONING" = "Принести/забрать утюг",
  "ADDITIONAL_SERVICES" = "Дополнительные услуги",
  "PREPARE_SAUNA" = "Забронировать посещение",
  "TAXI" = "Заказать трансфер",
  "OPEN_PARKING" = "Открыть парковку",
  "SHOP" = "Магазин отеля",
  "LEAVE_REVIEW" = "Оставить отзыв",
  "STAFF_HELP" = "Помощь техничнского персонала",
  "CLEANING" = "Желаемое время уборки",
}

export enum CategoryLabel {
  "CHAT" = "chat",
  "RECEPTION" = "reception",
  "RESTAURANT" = "restaurant",
  "ROOM_SERVICE" = "room_service",
  "SPA" = "spa",
  "SHOP" = "shop",
}

export enum RequestTypeLabel {
  "FOOD_ORDER" = "ordering_food",
  "BRING_DISHES" = "request_dishes",
  "WASH_DISHES" = "remove_dirty_dishes",
  "IRONING" = "bring_pick_up_an_iron_and_ironing_board",
  "ADDITIONAL_SERVICES" = "additional_services",
  "PREPARE_SAUNA" = "book_a_visit",
  "TAXI" = "request_transfer",
  "OPEN_PARKING" = "open_the_parking_lot",
  "SHOP" = "shop",
  "LEAVE_REVIEW" = "leave_feedback",
  "STAFF_HELP" = "staff_help",
  "CLEANING" = "room_cleaning",
}

export const getNextStatus = (current: keyof typeof RequestStatus) => {
  let currentStatus = "";
  let nextStatus: RequestStatus | "" = "";
  switch (current) {
    case "CREATED":
      currentStatus = RequestStatus.CREATED;
      nextStatus = RequestStatus.ACCEPTED;
      break;
    case "ACCEPTED":
      currentStatus = RequestStatus.ACCEPTED;
      nextStatus = RequestStatus.COMPLETED;
      break;

    case "COMPLETED":
      currentStatus = RequestStatus.COMPLETED;
      nextStatus = "";
      break;
  }
  return { currentStatus, nextStatus };
};

export const MAILER = {
  noReply: {
    email: "no-reply@aconite.io",
    name: "Aconite",
  },

  support: {
    email: "support@aconite.io",
    name: "Help Support",
  },
};

export const DEFAULT_MODULES = [
  {
    index: 1,
    title: "restaurant", // Replaced name: "restaurant" with id: "RESTAURANT"
    name: "RESTAURANT",
    value: true,
    subModules: [
      {
        moduleId: "RESTAURANT",
        title: "menu", // Replaced name: "restaurantMenu" with id: "FOOD_ORDER"
        value: true,
        name: "FOOD_ORDER",
      },
      {
        moduleId: "RESTAURANT",
        title: "request_dishes", // Replaced name: "restaurantAskDishes" with id: "BRING_DISHES"
        value: true,
        name: "BRING_DISHES",
      },
      {
        moduleId: "RESTAURANT",
        title: "remove_dirty_dishes", // Replaced name: "restaurantTakeAwayDishes" with id: "WASH_DISHES"
        value: true,
        name: "WASH_DISHES",
      },
    ],
  },
  {
    index: 2,
    title: "room_service", // Replaced name: "roomService" with id: "ROOM_SERVICE"
    name: "ROOM_SERVICE",
    value: true,
    subModules: [
      {
        moduleId: "ROOM_SERVICE",
        title: "bring_pick_up_an_iron_and_ironing_board", // Replaced name: "roomServiceIron" with id: "IRONING"
        value: true,
        name: "IRONING",
      },
      {
        moduleId: "ROOM_SERVICE",
        title: "staff_help", // Replaced name: "roomServiceTechical" with id: "STAFF_HELP"
        value: true,
        name: "STAFF_HELP",
      },
      {
        moduleId: "ROOM_SERVICE",
        title: "room_cleaning", // Newly added id: "CLEANING"
        value: true,
        name: "CLEANING",
      },
      {
        moduleId: "ROOM_SERVICE",
        title: "additional_services", // Replaced name: "roomServiceAdditionals" with id: "ADDITIONAL_SERVICES"
        value: true,
        name: "ADDITIONAL_SERVICES",
      },
    ],
  },
  {
    index: 3,
    title: "reception", // Replaced name: "reception" with id: "RECEPTION"
    name: "RECEPTION",
    value: true,
    subModules: [
      {
        moduleId: "RECEPTION",
        title: "request_transfer", // Replaced name: "receptionTransfer" with id: "TAXI"
        value: true,
        name: "TAXI",
      },
      {
        moduleId: "RECEPTION",
        title: "shop", // Replaced name: "receptionShop" with id: "SHOP"
        value: true,
        name: "SHOP",
      },
      {
        moduleId: "RECEPTION",
        title: "leave_feedback", // Replaced name: "receptionFeedback" with id: "LEAVE_REVIEW"
        value: true,
        name: "LEAVE_REVIEW",
      },
    ],
  },
  {
    index: 4,
    title: "chat",
    name: "CHAT",
    value: true,
    subModules: [],
  },
  {
    index: 5,
    title: "spa",
    name: "SPA",
    value: true,
    subModules: [
      {
        moduleId: "SPA",
        title: "book_a_visit", // Replaced name: "receptionShop" with id: "SHOP"
        value: true,
        hidden: true,
        name: "PREPARE_SAUNA",
      },
    ],
  },
  {
    index: 6,
    title: "shop",
    name: "SHOP",
    value: true,
    subModules: [
      {
        moduleId: "SHOP",
        title: "shop", // Replaced name: "receptionShop" with id: "SHOP"
        value: true,
        hidden: true,
        name: "HIDDEN_SHOP",
      },
    ],
  },
];

export const countryTranslations: Record<string, string> = {
  Afghanistan: "Афганистан",
  Albania: "Албания",
  Algeria: "Алжир",
  Andorra: "Андорра",
  Angola: "Ангола",
  "Antigua and Barbuda": "Антигуа и Барбуда",
  Argentina: "Аргентина",
  Armenia: "Армения",
  Australia: "Австралия",
  Austria: "Австрия",
  Azerbaijan: "Азербайджан",
  "The Bahamas": "Багамы",
  Bahrain: "Бахрейн",
  Bangladesh: "Бангладеш",
  Barbados: "Барбадос",
  Belarus: "Беларусь",
  Belgium: "Бельгия",
  Belize: "Белиз",
  Benin: "Бенин",
  Bhutan: "Бутан",
  Bolivia: "Боливия",
  "Bosnia and Herzegovina": "Босния и Герцеговина",
  Botswana: "Ботсвана",
  Brazil: "Бразилия",
  Brunei: "Бруней",
  Bulgaria: "Болгария",
  "Burkina Faso": "Буркина-Фасо",
  Burundi: "Бурунди",
  "Cabo Verde": "Кабо-Верде",
  Cambodia: "Камбоджа",
  Cameroon: "Камерун",
  Canada: "Канада",
  "Central African Republic": "Центральноафриканская Республика",
  Chad: "Чад",
  Chile: "Чили",
  China: "Китай",
  Colombia: "Колумбия",
  Comoros: "Коморы",
  "Congo, Democratic Republic of the": "Конго, Демократическая Республика",
  "Congo, Republic of the": "Конго, Республика",
  "Costa Rica": "Коста-Рика",
  "Côte d’Ivoire": "Кот-д’Ивуар",
  Croatia: "Хорватия",
  Cuba: "Куба",
  Cyprus: "Кипр",
  "Czech Republic": "Чешская Республика",
  Denmark: "Дания",
  Djibouti: "Джибути",
  Dominica: "Доминика",
  "Dominican Republic": "Доминиканская Республика",
  "East Timor (Timor-Leste)": "Восточный Тимор (Тимор-Лешти)",
  Ecuador: "Эквадор",
  Egypt: "Египет",
  "El Salvador": "Сальвадор",
  "Equatorial Guinea": "Экваториальная Гвинея",
  Eritrea: "Эритрея",
  Estonia: "Эстония",
  Eswatini: "Эсватини",
  Ethiopia: "Эфиопия",
  Fiji: "Фиджи",
  Finland: "Финляндия",
  France: "Франция",
  Gabon: "Габон",
  "The Gambia": "Гамбия",
  Georgia: "Грузия",
  Germany: "Германия",
  Ghana: "Гана",
  Greece: "Греция",
  Grenada: "Гренада",
  Guatemala: "Гватемала",
  Guinea: "Гвинея",
  "Guinea-Bissau": "Гвинея-Бисау",
  Guyana: "Гайана",
  Haiti: "Гаити",
  Honduras: "Гондурас",
  Hungary: "Венгрия",
  Iceland: "Исландия",
  India: "Индия",
  Indonesia: "Индонезия",
  Iran: "Иран",
  Iraq: "Ирак",
  Ireland: "Ирландия",
  Israel: "Израиль",
  Italy: "Италия",
  Jamaica: "Ямайка",
  Japan: "Япония",
  Jordan: "Иордания",
  Kazakhstan: "Казахстан",
  Kenya: "Кения",
  Kiribati: "Кирибати",
  "Korea, North": "Корея, Северная",
  "Korea, South": "Корея, Южная",
  Kosovo: "Косово",
  Kuwait: "Кувейт",
  Kyrgyzstan: "Киргизия",
  Laos: "Лаос",
  Latvia: "Латвия",
  Lebanon: "Ливан",
  Lesotho: "Лесото",
  Liberia: "Либерия",
  Libya: "Ливия",
  Liechtenstein: "Лихтенштейн",
  Lithuania: "Литва",
  Luxembourg: "Люксембург",
  Madagascar: "Мадагаскар",
  Malawi: "Малави",
  Malaysia: "Малайзия",
  Maldives: "Мальдивы",
  Mali: "Мали",
  Malta: "Мальта",
  "Marshall Islands": "Маршалловы острова",
  Mauritania: "Мавритания",
  Mauritius: "Маврикий",
  Mexico: "Мексика",
  "Micronesia, Federated States of": "Микронезия, Федеративные Штаты",
  Moldova: "Молдова",
  Monaco: "Монако",
  Mongolia: "Монголия",
  Montenegro: "Черногория",
  Morocco: "Марокко",
  Mozambique: "Мозамбик",
  "Myanmar (Burma)": "Мьянма (Бирма)",
  Namibia: "Намибия",
  Nauru: "Науру",
  Nepal: "Непал",
  Netherlands: "Нидерланды",
  "New Zealand": "Новая Зеландия",
  Nicaragua: "Никарагуа",
  Niger: "Нигер",
  Nigeria: "Нигерия",
  "North Macedonia": "Северная Македония",
  Norway: "Норвегия",
  Oman: "Оман",
  Pakistan: "Пакистан",
  Palau: "Палау",
  Panama: "Панама",
  "Papua New Guinea": "Папуа-Новая Гвинея",
  Paraguay: "Парагвай",
  Peru: "Перу",
  Philippines: "Филиппины",
  Poland: "Польша",
  Portugal: "Португалия",
  Qatar: "Катар",
  Romania: "Румыния",
  Russia: "Россия",
  Rwanda: "Руанда",
  "Saint Kitts and Nevis": "Сент-Китс и Невис",
  "Saint Lucia": "Сент-Люсия",
  "Saint Vincent and the Grenadines": "Сент-Винсент и Гренадины",
  Samoa: "Самоа",
  "San Marino": "Сан-Марино",
  "Sao Tome and Principe": "Сан-Томе и Принсипи",
  "Saudi Arabia": "Саудовская Аравия",
  Senegal: "Сенегал",
  Serbia: "Сербия",
  Seychelles: "Сейшельские острова",
  "Sierra Leone": "Сьерра-Леоне",
  Singapore: "Сингапур",
  Slovakia: "Словакия",
  Slovenia: "Словения",
  "Solomon Islands": "Соломоновы острова",
  Somalia: "Сомали",
  "South Africa": "Южная Африка",
  Spain: "Испания",
  "Sri Lanka": "Шри-Ланка",
  Sudan: "Судан",
  "Sudan, South": "Южный Судан",
  Suriname: "Суринам",
  Sweden: "Швеция",
  Switzerland: "Швейцария",
  Syria: "Сирия",
  Taiwan: "Тайвань",
  Tajikistan: "Таджикистан",
  Tanzania: "Танзания",
  Thailand: "Таиланд",
  Togo: "Того",
  Tonga: "Тонга",
  "Trinidad and Tobago": "Тринидад и Тобаго",
  Tunisia: "Тунис",
  Turkey: "Турция",
  Turkmenistan: "Туркменистан",
  Tuvalu: "Тувалу",
  Uganda: "Уганда",
  Ukraine: "Украина",
  "United Arab Emirates": "Объединенные Арабские Эмираты",
  "United Kingdom": "Соединенное Королевство",
  "United States": "Соединенные Штаты Америки",
  Uruguay: "Уругвай",
  Uzbekistan: "Узбекистан",
  Vanuatu: "Вануату",
  "Vatican City": "Ватикан",
  Venezuela: "Венесуэла",
  Vietnam: "Вьетнам",
  Yemen: "Йемен",
  Zambia: "Замбия",
  Zimbabwe: "Зимбабве",
};

export const COUNTRY_OPTIONS = [
  { label: "Afghanistan", value: "AF" },
  { label: "Åland Islands", value: "AX" },
  { label: "Albania", value: "AL" },
  { label: "Algeria", value: "DZ" },
  { label: "American Samoa", value: "AS" },
  { label: "Andorra", value: "AD" },
  { label: "Angola", value: "AO" },
  { label: "Anguilla", value: "AI" },
  { label: "Antarctica", value: "AQ" },
  { label: "Antigua and Barbuda", value: "AG" },
  { label: "Argentina", value: "AR" },
  { label: "Armenia", value: "AM" },
  { label: "Aruba", value: "AW" },
  { label: "Australia", value: "AU" },
  { label: "Austria", value: "AT" },
  { label: "Azerbaijan", value: "AZ" },
  { label: "Bahamas", value: "BS" },
  { label: "Bahrain", value: "BH" },
  { label: "Bangladesh", value: "BD" },
  { label: "Barbados", value: "BB" },
  { label: "Belarus", value: "BY" },
  { label: "Belgium", value: "BE" },
  { label: "Belize", value: "BZ" },
  { label: "Benin", value: "BJ" },
  { label: "Bermuda", value: "BM" },
  { label: "Bhutan", value: "BT" },
  { label: "Bolivia", value: "BO" },
  { label: "Bosnia and Herzegovina", value: "BA" },
  { label: "Botswana", value: "BW" },
  { label: "Bouvet Island", value: "BV" },
  { label: "Brazil", value: "BR" },
  { label: "British Indian Ocean Territory", value: "IO" },
  { label: "Brunei Darussalam", value: "BN" },
  { label: "Bulgaria", value: "BG" },
  { label: "Burkina Faso", value: "BF" },
  { label: "Burundi", value: "BI" },
  { label: "Cambodia", value: "KH" },
  { label: "Cameroon", value: "CM" },
  { label: "Canada", value: "CA" },
  { label: "Cape Verde", value: "CV" },
  { label: "Cayman Islands", value: "KY" },
  { label: "Central African Republic", value: "CF" },
  { label: "Chad", value: "TD" },
  { label: "Chile", value: "CL" },
  { label: "China", value: "CN" },
  { label: "Christmas Island", value: "CX" },
  { label: "Cocos (Keeling) Islands", value: "CC" },
  { label: "Colombia", value: "CO" },
  { label: "Comoros", value: "KM" },
  { label: "Congo", value: "CG" },
  { label: "Congo, The Democratic Republic of the", value: "CD" },
  { label: "Cook Islands", value: "CK" },
  { label: "Costa Rica", value: "CR" },
  { label: "Cote D'Ivoire", value: "CI" },
  { label: "Croatia", value: "HR" },
  { label: "Cuba", value: "CU" },
  { label: "Cyprus", value: "CY" },
  { label: "Czech Republic", value: "CZ" },
  { label: "Denmark", value: "DK" },
  { label: "Djibouti", value: "DJ" },
  { label: "Dominica", value: "DM" },
  { label: "Dominican Republic", value: "DO" },
  { label: "Ecuador", value: "EC" },
  { label: "Egypt", value: "EG" },
  { label: "El Salvador", value: "SV" },
  { label: "Equatorial Guinea", value: "GQ" },
  { label: "Eritrea", value: "ER" },
  { label: "Estonia", value: "EE" },
  { label: "Ethiopia", value: "ET" },
  { label: "Falkland Islands (Malvinas)", value: "FK" },
  { label: "Faroe Islands", value: "FO" },
  { label: "Fiji", value: "FJ" },
  { label: "Finland", value: "FI" },
  { label: "France", value: "FR" },
  { label: "French Guiana", value: "GF" },
  { label: "French Polynesia", value: "PF" },
  { label: "French Southern Territories", value: "TF" },
  { label: "Gabon", value: "GA" },
  { label: "Gambia", value: "GM" },
  { label: "Georgia", value: "GE" },
  { label: "Germany", value: "DE" },
  { label: "Ghana", value: "GH" },
  { label: "Gibraltar", value: "GI" },
  { label: "Greece", value: "GR" },
  { label: "Greenland", value: "GL" },
  { label: "Grenada", value: "GD" },
  { label: "Guadeloupe", value: "GP" },
  { label: "Guam", value: "GU" },
  { label: "Guatemala", value: "GT" },
  { label: "Guernsey", value: "GG" },
  { label: "Guinea", value: "GN" },
  { label: "Guinea-Bissau", value: "GW" },
  { label: "Guyana", value: "GY" },
  { label: "Haiti", value: "HT" },
  { label: "Heard Island and Mcdonald Islands", value: "HM" },
  { label: "Holy See (Vatican City State)", value: "VA" },
  { label: "Honduras", value: "HN" },
  { label: "Hong Kong", value: "HK" },
  { label: "Hungary", value: "HU" },
  { label: "Iceland", value: "IS" },
  { label: "India", value: "IN" },
  { label: "Indonesia", value: "ID" },
  { label: "Iran, Islamic Republic Of", value: "IR" },
  { label: "Iraq", value: "IQ" },
  { label: "Ireland", value: "IE" },
  { label: "Isle of Man", value: "IM" },
  { label: "Israel", value: "IL" },
  { label: "Italy", value: "IT" },
  { label: "Jamaica", value: "JM" },
  { label: "Japan", value: "JP" },
  { label: "Jersey", value: "JE" },
  { label: "Jordan", value: "JO" },
  { label: "Kazakhstan", value: "KZ" },
  { label: "Kenya", value: "KE" },
  { label: "Kiribati", value: "KI" },
  { label: "Korea, Democratic People'S Republic of", value: "KP" },
  { label: "Korea, Republic of", value: "KR" },
  { label: "Kuwait", value: "KW" },
  { label: "Kyrgyzstan", value: "KG" },
  { label: "Lao People'S Democratic Republic", value: "LA" },
  { label: "Latvia", value: "LV" },
  { label: "Lebanon", value: "LB" },
  { label: "Lesotho", value: "LS" },
  { label: "Liberia", value: "LR" },
  { label: "Libyan Arab Jamahiriya", value: "LY" },
  { label: "Liechtenstein", value: "LI" },
  { label: "Lithuania", value: "LT" },
  { label: "Luxembourg", value: "LU" },
  { label: "Macao", value: "MO" },
  { label: "Macedonia, The Former Yugoslav Republic of", value: "MK" },
  { label: "Madagascar", value: "MG" },
  { label: "Malawi", value: "MW" },
  { label: "Malaysia", value: "MY" },
  { label: "Maldives", value: "MV" },
  { label: "Mali", value: "ML" },
  { label: "Malta", value: "MT" },
  { label: "Marshall Islands", value: "MH" },
  { label: "Martinique", value: "MQ" },
  { label: "Mauritania", value: "MR" },
  { label: "Mauritius", value: "MU" },
  { label: "Mayotte", value: "YT" },
  { label: "Mexico", value: "MX" },
  { label: "Micronesia, Federated States of", value: "FM" },
  { label: "Moldova, Republic of", value: "MD" },
  { label: "Monaco", value: "MC" },
  { label: "Mongolia", value: "MN" },
  { label: "Montserrat", value: "MS" },
  { label: "Morocco", value: "MA" },
  { label: "Mozambique", value: "MZ" },
  { label: "Myanmar", value: "MM" },
  { label: "Namibia", value: "NA" },
  { label: "Nauru", value: "NR" },
  { label: "Nepal", value: "NP" },
  { label: "Netherlands", value: "NL" },
  { label: "Netherlands Antilles", value: "AN" },
  { label: "New Caledonia", value: "NC" },
  { label: "New Zealand", value: "NZ" },
  { label: "Nicaragua", value: "NI" },
  { label: "Niger", value: "NE" },
  { label: "Nigeria", value: "NG" },
  { label: "Niue", value: "NU" },
  { label: "Norfolk Island", value: "NF" },
  { label: "Northern Mariana Islands", value: "MP" },
  { label: "Norway", value: "NO" },
  { label: "Oman", value: "OM" },
  { label: "Pakistan", value: "PK" },
  { label: "Palau", value: "PW" },
  { label: "Palestinian Territory, Occupied", value: "PS" },
  { label: "Panama", value: "PA" },
  { label: "Papua New Guinea", value: "PG" },
  { label: "Paraguay", value: "PY" },
  { label: "Peru", value: "PE" },
  { label: "Philippines", value: "PH" },
  { label: "Pitcairn", value: "PN" },
  { label: "Poland", value: "PL" },
  { label: "Portugal", value: "PT" },
  { label: "Puerto Rico", value: "PR" },
  { label: "Qatar", value: "QA" },
  { label: "Reunion", value: "RE" },
  { label: "Romania", value: "RO" },
  { label: "Russian Federation", value: "RU" },
  { label: "RWANDA", value: "RW" },
  { label: "Saint Helena", value: "SH" },
  { label: "Saint Kitts and Nevis", value: "KN" },
  { label: "Saint Lucia", value: "LC" },
  { label: "Saint Pierre and Miquelon", value: "PM" },
  { label: "Saint Vincent and the Grenadines", value: "VC" },
  { label: "Samoa", value: "WS" },
  { label: "San Marino", value: "SM" },
  { label: "Sao Tome and Principe", value: "ST" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Senegal", value: "SN" },
  { label: "Serbia and Montenegro", value: "CS" },
  { label: "Seychelles", value: "SC" },
  { label: "Sierra Leone", value: "SL" },
  { label: "Singapore", value: "SG" },
  { label: "Slovakia", value: "SK" },
  { label: "Slovenia", value: "SI" },
  { label: "Solomon Islands", value: "SB" },
  { label: "Somalia", value: "SO" },
  { label: "South Africa", value: "ZA" },
  { label: "South Georgia and the South Sandwich Islands", value: "GS" },
  { label: "Spain", value: "ES" },
  { label: "Sri Lanka", value: "LK" },
  { label: "Sudan", value: "SD" },
  { label: "Suriname", value: "SR" },
  { label: "Svalbard and Jan Mayen", value: "SJ" },
  { label: "Swaziland", value: "SZ" },
  { label: "Sweden", value: "SE" },
  { label: "Switzerland", value: "CH" },
  { label: "Syrian Arab Republic", value: "SY" },
  { label: "Taiwan, Province of China", value: "TW" },
  { label: "Tajikistan", value: "TJ" },
  { label: "Tanzania, United Republic of", value: "TZ" },
  { label: "Thailand", value: "TH" },
  { label: "Timor-Leste", value: "TL" },
  { label: "Togo", value: "TG" },
  { label: "Tokelau", value: "TK" },
  { label: "Tonga", value: "TO" },
  { label: "Trinidad and Tobago", value: "TT" },
  { label: "Tunisia", value: "TN" },
  { label: "Turkey", value: "TR" },
  { label: "Turkmenistan", value: "TM" },
  { label: "Turks and Caicos Islands", value: "TC" },
  { label: "Tuvalu", value: "TV" },
  { label: "Uganda", value: "UG" },
  { label: "Ukraine", value: "UA" },
  { label: "United Arab Emirates", value: "AE" },
  { label: "United Kingdom", value: "GB" },
  { label: "United States", value: "US" },
  { label: "United States Minor Outlying Islands", value: "UM" },
  { label: "Uruguay", value: "UY" },
  { label: "Uzbekistan", value: "UZ" },
  { label: "Vanuatu", value: "VU" },
  { label: "Venezuela", value: "VE" },
  { label: "Viet Nam", value: "VN" },
  { label: "Virgin Islands, British", value: "VG" },
  { label: "Virgin Islands, U.S.", value: "VI" },
  { label: "Wallis and Futuna", value: "WF" },
  { label: "Western Sahara", value: "EH" },
  { label: "Yemen", value: "YE" },
  { label: "Zambia", value: "ZM" },
  { label: "Zimbabwe", value: "ZW" },
];
